// lib/types.ts
//
// Single source of truth for all shared TypeScript types in the project.
// If a shape is used in more than one file, it lives here.

/**
 * Supported document types in the system.
 *
 * "prd" is the only one fully implemented in the MVP.
 * "tech-spec" and "meeting-notes" are architecturally supported but stubbed.
 *
 * Using a union of string literals (instead of an enum) keeps things simple
 * and TypeScript can narrow types based on the value at compile time.
 */
export type DocType = "prd" | "tech-spec" | "meeting-notes";

/**
 * One entry in the doc-type registry.
 * The UI uses these to render the doc-type selector cards.
 */
export interface DocTypeInfo {
  id: DocType;
  label: string;        // Human-readable name (e.g., "Product Requirements")
  description: string;  // Short tagline shown on the selector card
  enabled: boolean;     // false => shows as "Coming soon", disabled in UI
}

/**
 * A clarifying question generated by the AI.
 * Returned by /api/clarify, used in the Clarify step.
 */
export interface Question {
  id: string;   // Stable identifier (e.g., "q1")
  text: string; // The question text
}

/**
 * A user's answer to a clarifying question.
 * The answer can be empty if the user clicked "Skip".
 */
export interface Answer {
  questionId: string;
  question: string;  // Echo of the question text (so generate route doesn't need to look it up)
  answer: string;    // May be empty string if skipped
}

/**
 * An assumption the AI flagged while generating a document.
 * Risk level helps the user prioritize what to verify.
 */
export interface Assumption {
  text: string;
  risk: "risky" | "reasonable";
}

/**
 * Result of evaluating a single rubric rule against the user's content.
 * Used in BOTH layers (prompt-quality and document-quality).
 */
export interface RuleResult {
  name: string;       // The rule, e.g., "Has clear problem statement"
  passed: boolean;    // Did the content satisfy this rule?
  evidence: string;   // 1-line explanation: quoted snippet or reason for failure
}

/**
 * Recommendation band attached to a trust score.
 * Both layers use the same shape but with slightly different wording.
 */
export interface ScoreOutcome {
  score: number;           // 0-100, integer
  recommendation: string;  // Human-readable guidance
}

/**
 * Response from POST /api/analyze-prompt (Layer 1: prompt quality).
 */
export interface PromptAnalysisResponse extends ScoreOutcome {
  rules: RuleResult[];
  suggestions: string[];   // 1-3 specific improvement suggestions
}

/**
 * Response from POST /api/clarify.
 * Just a list of questions the AI thinks the user should answer.
 */
export interface ClarifyResponse {
  questions: string[];
}

/**
 * Response from POST /api/generate.
 * Returns the markdown document + the assumptions the AI made.
 */
export interface GenerateResponse {
  document: string;            // Full markdown content
  assumptions: Assumption[];
}

/**
 * Response from POST /api/validate (Layer 2: document quality).
 */
export interface ValidateResponse extends ScoreOutcome {
  rules: RuleResult[];
}

/**
 * Aggregated result shown on the Review screen.
 * Combines outputs of analyze-prompt + generate + validate into
 * a single object the UI can render.
 */
export interface ReviewBundle {
  docType: DocType;
  document: string;
  assumptions: Assumption[];
  promptLayer: PromptAnalysisResponse;
  documentLayer: ValidateResponse;
}
